/**
 * Words the grammar owns.
 *
 * Naming a feature after one of these is not a style problem: `attribute
 * objective` is read as the start of an objective clause and the file stops
 * parsing several lines later, with a diagnostic that points at the wrong
 * place. Measured while writing the reference models (register §E) — every one
 * of these cost a debugging round there, so an authoring agent is told about
 * them up front and the preflight refuses them before Sysprose ever sees them.
 */
export const RESERVED_FEATURE_NAMES = [
  // The ones measured to collide first: a model names its things after what
  // they do, and these are verbs the grammar owns.
  'message',
  'objective',
  'assign',
  'event',
  'subject',
  'actor',
  'doc',
  'part',
  'port',
  'item',
  'action',
  'state',
  'flow',
  'connection',
  'interface',
  'requirement',
  'constraint',
  'attribute',
  'package',
  'metadata',
  'occurrence',
  'individual',
  'snapshot',
  'timeslice',
  'view',
  'viewpoint',
  'concern',
  'rendering',
  'verification',
  'analysis',
  'calc',
  'enum',
  'variation',
  'variant',
  'ref',
  'in',
  'out',
  'inout',
  'first',
  'then',
  'accept',
  'send',
  'perform',
  'exhibit',
  'include',
  'satisfy',
  'allocate',
  'trace',
  'refine',
  'derive',
  'verify',
  'assume',
  'require',
  'return',
  'bind',
  'connect',
  'expose',
  'import',
  'about',
  'via',
  'to',
  'from',
  'of',
  'by',
  'if',
  'else',
  'do',
  'entry',
  'exit',
  'abstract',
  'readonly',
  'derived',
  'end',
  'succession',
  'transition',
  'decide',
  'merge',
  'join',
  'fork',
  'assert',
  'not',
  'and',
  'or',
  'xor',
  'null',
  'true',
  'false',
  'while',
  'for',
  'loop',
  'until',
  'terminate',
  'return',
  'filter',
  'alias',
  'library',
  'standard',
  'dependency',
  'comment',
  'rep',
  'language',
  'locale',
  'all',
  'nonunique',
  'ordered',
  'redefines',
  'subsets',
  'references',
  'specializes',
  'conjugates',
  'chains',
  'inverse',
  'featured',
  'typed',
  'defined',
  'frame',
  'render',
  'hastype',
  'istype',
  'meta',
  'as',
  'implies',
  'new',
  'private',
  'public',
  'protected',
  'portion',
  'transition',
  'stream',
  'parallel',
  'default',
  'const',
  'end',
] as const;

const RESERVED = new Set<string>(RESERVED_FEATURE_NAMES);

export const isReservedName = (name: string): boolean => RESERVED.has(name);
